# Generated by Django 3.1.4 on 2021-06-18 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profilemodel_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='permissions',
            new_name='permission',
        ),
    ]
