# Generated by Django 3.1.4 on 2021-06-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210618_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='permission',
            field=models.IntegerField(choices=[(0, 'Student'), (1, 'Mentor'), (2, 'Admin')]),
        ),
    ]
