# Generated by Django 3.2.4 on 2021-07-06 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(0, 'Video'), (1, 'Books')])),
                ('title', models.CharField(max_length=255)),
                ('preview', models.ImageField(upload_to='knowledge')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.TextField()),
                ('kn_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.knowledgebase')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.FileField(upload_to='knowledge/books')),
                ('kn_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.knowledgebase')),
            ],
        ),
    ]
