# Generated by Django 3.2.4 on 2021-07-06 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KnowledgeBase',
            new_name='KnowledgeBaseModel',
        ),
        migrations.RenameModel(
            old_name='KnowledgeBook',
            new_name='KnowledgeBookModel',
        ),
        migrations.RenameModel(
            old_name='KnowledgeVideo',
            new_name='KnowledgeVideoModel',
        ),
    ]
