# Generated by Django 3.2.4 on 2021-07-06 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210706_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgebasemodel',
            options={'verbose_name': 'knowledge base', 'verbose_name_plural': 'knowledge base'},
        ),
        migrations.AlterModelOptions(
            name='knowledgebookmodel',
            options={'verbose_name': 'knowledge book', 'verbose_name_plural': 'knowledge books'},
        ),
        migrations.AlterModelOptions(
            name='knowledgevideomodel',
            options={'verbose_name': 'knowledge video', 'verbose_name_plural': 'knowledge videos'},
        ),
    ]
