# Generated by Django 3.2.4 on 2021-07-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_knowledgevideomodel_kn_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebookmodel',
            name='description',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledgevideomodel',
            name='description',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='knowledgebookmodel',
            name='book',
            field=models.TextField(),
        ),
    ]
