# Generated by Django 3.2.4 on 2021-07-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210726_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebookmodel',
            name='title',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
    ]
