# Generated by Django 3.2.4 on 2021-07-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_knowledgebookmodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgevideomodel',
            name='title',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
    ]
