# Generated by Django 3.2.4 on 2021-07-26 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_knowledgevideomodel_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgevideomodel',
            name='title',
        ),
    ]
