# Generated by Django 3.2.6 on 2021-09-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_notificationmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationmodel',
            name='from_user',
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='seen',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
