# Generated by Django 3.2.6 on 2021-09-13 06:11

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20210903_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='notificationmodel',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at', 'updated_at'], name='dashboard_n_created_4764b2_brin'),
        ),
    ]
