# Generated by Django 3.2.6 on 2021-09-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20210913_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebookmodel',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='knowledge/book'),
        ),
        migrations.AddField(
            model_name='knowledgevideomodel',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='knowledge/video'),
        ),
        migrations.AddField(
            model_name='knowledgevideomodel',
            name='title',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='knowledgebookmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='knowledgevideomodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
