# Generated by Django 3.2.6 on 2021-09-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20210921_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationmodel',
            name='text',
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='course',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='full_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='lesson',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='type',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
