# Generated by Django 3.2.6 on 2021-09-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_ordermodel_click_trans_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='amount',
            field=models.FloatField(),
        ),
    ]
