# Generated by Django 3.2.6 on 2021-10-12 11:51

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0106_coursemodel_github'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0017_alter_ordermodel_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='PaymeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('paycom_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('paycom_time', models.CharField(blank=True, max_length=100, null=True)),
                ('paycom_time_datetime', models.DateTimeField(blank=True, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('perform_time', models.DateTimeField(blank=True, null=True)),
                ('cancel_time', models.DateTimeField(blank=True, null=True)),
                ('amount', models.IntegerField()),
                ('status_payment', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.coursemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='paymemodel',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at', 'updated_at'], name='dashboard_p_created_83cf93_brin'),
        ),
    ]
