# Generated by Django 3.2.6 on 2021-10-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20211012_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymemodel',
            name='reason',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
