# Generated by Django 3.2.4 on 2021-06-25 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('image_course_title', models.CharField(max_length=50)),
                ('image_teacher_title', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='courses')),
                ('duration', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('structure_1', models.CharField(max_length=200)),
                ('structure_2', models.CharField(max_length=200)),
                ('structure_3', models.CharField(max_length=200)),
                ('structure_4', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
            },
        ),
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='feedbacks')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'feedback',
                'verbose_name_plural': 'feedbacks',
            },
        ),
        migrations.CreateModel(
            name='LessonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='courses.coursemodel')),
            ],
            options={
                'verbose_name': 'lesson',
                'verbose_name_plural': 'lessons',
            },
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='teachers')),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'teacher',
                'verbose_name_plural': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='TestChapterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField(choices=[(0, 'One answer'), (1, 'Multiple answer'), (2, 'Short')])),
                ('question', models.CharField(max_length=500)),
                ('feedback_true', models.CharField(max_length=500)),
                ('feedback_false', models.CharField(max_length=500)),
                ('short_answer', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'test chapter',
                'verbose_name_plural': 'test chapters',
            },
        ),
        migrations.CreateModel(
            name='TestIntroModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.JSONField()),
            ],
            options={
                'verbose_name': 'test intro',
                'verbose_name_plural': 'test intros',
            },
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='courses.lessonmodel')),
            ],
            options={
                'verbose_name': 'test',
                'verbose_name_plural': 'tests',
            },
        ),
        migrations.CreateModel(
            name='TheoryChapterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.JSONField()),
            ],
            options={
                'verbose_name': 'theory chapter',
                'verbose_name_plural': 'theory chapters',
            },
        ),
        migrations.CreateModel(
            name='TheoryIntroModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.JSONField()),
            ],
            options={
                'verbose_name': 'theory intro',
                'verbose_name_plural': 'theory intros',
            },
        ),
        migrations.CreateModel(
            name='TheoryLabChapterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('embed', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'theory lab',
                'verbose_name_plural': 'theory labs',
            },
        ),
        migrations.CreateModel(
            name='TheoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theory', to='courses.lessonmodel')),
            ],
            options={
                'verbose_name': 'theory',
                'verbose_name_plural': 'theories',
            },
        ),
        migrations.CreateModel(
            name='UserTheoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(db_index=True, default=False)),
                ('theory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.theorymodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user theory',
                'verbose_name_plural': 'user theories',
            },
        ),
        migrations.CreateModel(
            name='UserTheoryLabModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(db_index=True, default=False)),
                ('points', models.PositiveIntegerField(blank=True, null=True)),
                ('theory_lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.theorylabchaptermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user theory lab',
                'verbose_name_plural': 'user theory labs',
            },
        ),
        migrations.CreateModel(
            name='UserTheoryIntroModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(db_index=True, default=False)),
                ('theory_intro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.theoryintromodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user theory intro',
                'verbose_name_plural': 'user theory intros',
            },
        ),
        migrations.CreateModel(
            name='UserTheoryChapterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(db_index=True, default=False)),
                ('theory_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.theorychaptermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user theory chapter',
                'verbose_name_plural': 'user theory chapters',
            },
        ),
        migrations.CreateModel(
            name='UserTestShortChapterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(db_index=True, default=False)),
                ('answered', models.CharField(blank=True, max_length=500, null=True)),
                ('correct', models.BooleanField(blank=True, null=True)),
                ('test_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.testchaptermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user test short',
                'verbose_name_plural': 'user test short',
            },
        ),
        migrations.CreateModel(
            name='UserTestOneChapterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(db_index=True, default=False)),
                ('answered', models.IntegerField(blank=True, null=True)),
                ('correct', models.BooleanField(blank=True, null=True)),
                ('test_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.testchaptermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user test one',
                'verbose_name_plural': 'user tests one',
            },
        ),
        migrations.CreateModel(
            name='UserTestMultipleChapterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(db_index=True, default=False)),
                ('answered', models.CharField(blank=True, max_length=500, null=True)),
                ('correct', models.BooleanField(blank=True, null=True)),
                ('test_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.testchaptermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user test multiple',
                'verbose_name_plural': 'user test multiples',
            },
        ),
        migrations.CreateModel(
            name='UserTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(db_index=True, default=False)),
                ('points', models.PositiveIntegerField(blank=True, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.testmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user test',
                'verbose_name_plural': 'user tests',
            },
        ),
        migrations.CreateModel(
            name='UserTestIntroModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(db_index=True, default=False)),
                ('test_intro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.testintromodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user test intro',
                'verbose_name_plural': 'user test intros',
            },
        ),
        migrations.CreateModel(
            name='UserLessonOverallModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points', models.PositiveIntegerField()),
                ('available', models.BooleanField(db_index=True, default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lessonmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user lesson overall',
                'verbose_name_plural': 'user lessons overall',
            },
        ),
        migrations.CreateModel(
            name='UserLessonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(db_index=True, default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lessonmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user lesson',
                'verbose_name_plural': 'user lessons',
            },
        ),
        migrations.CreateModel(
            name='UserBoughtCourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursemodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user bought',
                'verbose_name_plural': 'user bought',
            },
        ),
        migrations.AddField(
            model_name='theorylabchaptermodel',
            name='theory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.theorymodel'),
        ),
        migrations.AddField(
            model_name='theoryintromodel',
            name='theory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.theorymodel'),
        ),
        migrations.AddField(
            model_name='theorychaptermodel',
            name='theory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.theorymodel'),
        ),
        migrations.CreateModel(
            name='TestVariantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.CharField(max_length=500)),
                ('answer', models.BooleanField(default=True)),
                ('test_one_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.testchaptermodel')),
            ],
            options={
                'verbose_name': 'test variant',
                'verbose_name_plural': 'test variants',
            },
        ),
        migrations.AddField(
            model_name='testintromodel',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.testmodel'),
        ),
        migrations.AddField(
            model_name='testchaptermodel',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.testmodel'),
        ),
        migrations.CreateModel(
            name='SliderMainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='sliders')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sliders', to='courses.coursemodel')),
            ],
            options={
                'verbose_name': 'slider main',
                'verbose_name_plural': 'slider main',
            },
        ),
        migrations.CreateModel(
            name='SliderChildModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='courses.slidermainmodel')),
            ],
            options={
                'verbose_name': 'slider child',
                'verbose_name_plural': 'slider children',
            },
        ),
        migrations.CreateModel(
            name='RequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField()),
                ('processed', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='courses.coursemodel')),
            ],
            options={
                'verbose_name': 'request',
                'verbose_name_plural': 'requests',
            },
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.teachermodel'),
        ),
    ]
