# Generated by Django 3.2.4 on 2021-06-25 12:00

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTipsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tip', models.CharField(max_length=255)),
                ('sub_tip', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'course tip',
                'verbose_name_plural': 'course tips',
            },
        ),
        migrations.CreateModel(
            name='UserAnsweredTestChapterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answered', models.TextField(blank=True, null=True)),
                ('correct', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'user answered test chapter',
                'verbose_name_plural': 'user answered tests chapter',
            },
        ),
        migrations.CreateModel(
            name='UserAnsweredTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'user answered test',
                'verbose_name_plural': 'user answered tests',
            },
        ),
        migrations.CreateModel(
            name='UserAnsweredTheoryLabModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'user answered theory lab',
                'verbose_name_plural': 'user answered theory labs',
            },
        ),
        migrations.CreateModel(
            name='UserGotLessonOverallModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'user got lesson overall',
                'verbose_name_plural': 'user got lessons overall',
            },
        ),
        migrations.CreateModel(
            name='UserTestChapterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'user test chapter',
                'verbose_name_plural': 'user tests chapter',
            },
        ),
        migrations.RemoveField(
            model_name='usertestmultiplechaptermodel',
            name='test_chapter',
        ),
        migrations.RemoveField(
            model_name='usertestmultiplechaptermodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usertestonechaptermodel',
            name='test_chapter',
        ),
        migrations.RemoveField(
            model_name='usertestonechaptermodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usertestshortchaptermodel',
            name='test_chapter',
        ),
        migrations.RemoveField(
            model_name='usertestshortchaptermodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userlessonoverallmodel',
            name='points',
        ),
        migrations.RemoveField(
            model_name='usertestmodel',
            name='points',
        ),
        migrations.RemoveField(
            model_name='usertheorylabmodel',
            name='points',
        ),
        migrations.AddField(
            model_name='userboughtcoursemodel',
            name='bought_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userboughtcoursemodel',
            name='expiration_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userboughtcoursemodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testintromodel',
            name='test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.testmodel'),
        ),
        migrations.AlterField(
            model_name='testintromodel',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='theorychaptermodel',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='theoryintromodel',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='theoryintromodel',
            name='theory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.theorymodel'),
        ),
        migrations.AlterField(
            model_name='userboughtcoursemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userboughtcoursemodel',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['bought_date', 'expiration_date'], name='courses_use_bought__7f666e_brin'),
        ),
        migrations.DeleteModel(
            name='UserTestMultipleChapterModel',
        ),
        migrations.DeleteModel(
            name='UserTestOneChapterModel',
        ),
        migrations.DeleteModel(
            name='UserTestShortChapterModel',
        ),
        migrations.AddField(
            model_name='usertestchaptermodel',
            name='test_chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.testchaptermodel'),
        ),
        migrations.AddField(
            model_name='usertestchaptermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usergotlessonoverallmodel',
            name='user_overall',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.userlessonoverallmodel'),
        ),
        migrations.AddField(
            model_name='useransweredtheorylabmodel',
            name='user_theory_lab',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.usertheorylabmodel'),
        ),
        migrations.AddField(
            model_name='useransweredtestmodel',
            name='user_test_model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.usertestmodel'),
        ),
        migrations.AddField(
            model_name='useransweredtestchaptermodel',
            name='user_test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.usertestchaptermodel'),
        ),
        migrations.AddField(
            model_name='coursetipsmodel',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tip', to='courses.coursemodel'),
        ),
    ]
