# Generated by Django 3.2.4 on 2021-06-28 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210625_1700'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBoughtCourseModel',
        ),
    ]
