# Generated by Django 3.2.4 on 2021-06-28 05:42

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_delete_userboughtcoursemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBoughtCourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('bought_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user bought',
                'verbose_name_plural': 'user bought',
            },
        ),
        migrations.AddIndex(
            model_name='userboughtcoursemodel',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['bought_date', 'expiration_date'], name='courses_use_bought__7f666e_brin'),
        ),
    ]
