# Generated by Django 3.2.4 on 2021-06-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20210628_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='phone',
            field=models.CharField(default=9989222222, max_length=40),
            preserve_default=False,
        ),
    ]
