# Generated by Django 3.2.4 on 2021-07-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_requestmodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermodel',
            name='description',
            field=models.TextField(),
        ),
    ]
