# Generated by Django 3.2.4 on 2021-07-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20210705_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergotlessonoverallmodel',
            name='enough',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
