# Generated by Django 3.2.4 on 2021-07-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_usergotlessonoverallmodel_enough'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestmodel',
            name='done',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='usertheorymodel',
            name='done',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
