# Generated by Django 3.2.4 on 2021-07-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20210705_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='useransweredtestmodel',
            name='enough',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
