# Generated by Django 3.2.4 on 2021-07-05 07:46

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_useransweredtestmodel_enough'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='tagmodel',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at', 'updated_at'], name='courses_tag_created_5f28d2_brin'),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='tag',
            field=models.ManyToManyField(to='courses.TagModel'),
        ),
    ]
