# Generated by Django 3.2.4 on 2021-07-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_lessonmodel_activation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonmodel',
            name='activation_date',
        ),
        migrations.AddField(
            model_name='lessonmodel',
            name='activation_day',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
