# Generated by Django 3.2.4 on 2021-07-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_userlessonmodel_activation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonmodel',
            name='activation_day',
            field=models.CharField(max_length=10),
        ),
    ]
