# Generated by Django 3.2.4 on 2021-07-05 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_alter_lessonmodel_activation_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonmodel',
            name='activated',
        ),
    ]
