# Generated by Django 3.2.4 on 2021-07-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_remove_lessonmodel_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlessonmodel',
            name='done',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
