# Generated by Django 3.2.4 on 2021-07-09 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_alter_lessonmodel_activation_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlessonoverallmodel',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='userlessonoverallmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='userlessonoverallmodel',
            name='user_lesson',
            field=models.ForeignKey(default=36, on_delete=django.db.models.deletion.CASCADE, to='courses.userlessonmodel'),
            preserve_default=False,
        ),
    ]
