# Generated by Django 3.2.4 on 2021-07-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_auto_20210709_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='testintromodel',
            name='image',
            field=models.ImageField(default=1, upload_to='test/intro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theorychaptermodel',
            name='title',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theoryintromodel',
            name='image',
            field=models.ImageField(default=1, upload_to='theory/intro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theoryintromodel',
            name='title',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
