# Generated by Django 3.2.4 on 2021-07-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_auto_20210713_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useransweredtheorylabmodel',
            name='points',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
