# Generated by Django 3.2.4 on 2021-07-14 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_alter_useransweredtheorylabmodel_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.teachermodel'),
        ),
    ]
