# Generated by Django 3.2.4 on 2021-07-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_alter_coursemodel_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonmodel',
            name='active',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
