# Generated by Django 3.2.4 on 2021-07-26 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0045_alter_coursemodel_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergotlessonoverallmodel',
            name='enough',
        ),
        migrations.AddField(
            model_name='lessonmodel',
            name='lab_percentage',
            field=models.IntegerField(default=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonmodel',
            name='test_percentage',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testmodel',
            name='control',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='minimum_percentage',
            field=models.PositiveIntegerField(default=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testmodel',
            name='timer',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theorylabchaptermodel',
            name='control',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='theorylabchaptermodel',
            name='minimum_points',
            field=models.PositiveIntegerField(default=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useransweredtheorylabmodel',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='theorylabchaptermodel',
            name='theory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.theorymodel'),
        ),
    ]
