# Generated by Django 3.2.4 on 2021-07-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0046_auto_20210726_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='useransweredtheorylabmodel',
            name='enough',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
