# Generated by Django 3.2.4 on 2021-07-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0048_auto_20210726_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlessonmodel',
            name='complete_time',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usertestmodel',
            name='complete_time',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usertheorychaptermodel',
            name='complete_time',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usertheorylabmodel',
            name='complete_time',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usertheorymodel',
            name='complete_time',
            field=models.TextField(),
        ),
    ]
