# Generated by Django 3.2.4 on 2021-07-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0049_auto_20210726_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlessonmodel',
            name='complete_time',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userlessonmodel',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userlessonmodel',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertestmodel',
            name='complete_time',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertestmodel',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertestmodel',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertheorychaptermodel',
            name='complete_time',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertheorychaptermodel',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertheorychaptermodel',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertheorylabmodel',
            name='complete_time',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertheorylabmodel',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertheorylabmodel',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertheorymodel',
            name='complete_time',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertheorymodel',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertheorymodel',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
