# Generated by Django 3.2.4 on 2021-07-28 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0052_usertestmodel_again'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useransweredtestmodel',
            name='user_test_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.usertestmodel'),
        ),
        migrations.AlterField(
            model_name='useransweredtheorylabmodel',
            name='user_theory_lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.usertheorylabmodel'),
        ),
    ]
