# Generated by Django 3.2.4 on 2021-07-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0054_editorimagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theorychaptermodel',
            name='text',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='theoryintromodel',
            name='text',
            field=models.JSONField(),
        ),
    ]
