# Generated by Django 3.2.4 on 2021-08-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0057_auto_20210730_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='testchaptermodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='test/chapter'),
        ),
        migrations.AddField(
            model_name='testchaptermodel',
            name='text',
            field=models.JSONField(default='a1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testchaptermodel',
            name='title',
            field=models.CharField(default='1', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testintromodel',
            name='greetings',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
    ]
