# Generated by Django 3.2.4 on 2021-08-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0058_auto_20210805_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='testintromodel',
            name='title',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
