# Generated by Django 3.2.4 on 2021-08-05 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0059_testintromodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='timer',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='theorylabchaptermodel',
            name='theory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.theorymodel'),
        ),
    ]
