# Generated by Django 3.2.4 on 2021-08-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0060_auto_20210805_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='control',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='theorylabchaptermodel',
            name='control',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
