# Generated by Django 3.2.4 on 2021-08-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0061_auto_20210805_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='minimum_percentage',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='theorylabchaptermodel',
            name='minimum_points',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
