# Generated by Django 3.2.4 on 2021-08-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0063_auto_20210805_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testchaptermodel',
            name='feedback_false',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testchaptermodel',
            name='feedback_true',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testchaptermodel',
            name='text',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
