# Generated by Django 3.2.4 on 2021-08-11 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0064_auto_20210810_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useransweredtestchaptermodel',
            name='answered',
        ),
    ]
