# Generated by Django 3.2.4 on 2021-08-12 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0066_auto_20210812_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlessonmodel',
            name='complete_time',
        ),
        migrations.RemoveField(
            model_name='usertestmodel',
            name='complete_time',
        ),
        migrations.RemoveField(
            model_name='usertheorychaptermodel',
            name='complete_time',
        ),
        migrations.RemoveField(
            model_name='usertheorylabmodel',
            name='complete_time',
        ),
        migrations.RemoveField(
            model_name='usertheorymodel',
            name='complete_time',
        ),
    ]
