# Generated by Django 3.2.4 on 2021-08-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0067_auto_20210812_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlessonmodel',
            name='complete_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertestmodel',
            name='complete_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertheorychaptermodel',
            name='complete_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertheorylabmodel',
            name='complete_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertheorymodel',
            name='complete_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
