# Generated by Django 3.2.4 on 2021-08-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0068_auto_20210812_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlessonmodel',
            name='activation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
