# Generated by Django 3.2.4 on 2021-08-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0070_auto_20210812_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='control',
            field=models.BooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='theorylabchaptermodel',
            name='control',
            field=models.BooleanField(db_index=True),
        ),
    ]
