# Generated by Django 3.2.4 on 2021-08-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0071_auto_20210812_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonmodel',
            name='description',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertestmodel',
            name='time_left',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertheorylabmodel',
            name='submitted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
