# Generated by Django 3.2.4 on 2021-08-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0073_auto_20210813_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestmodel',
            name='start',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
