# Generated by Django 3.2.4 on 2021-08-16 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0076_usertestmodel_time_left'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertestmodel',
            name='time_left',
        ),
    ]
