# Generated by Django 3.2.4 on 2021-08-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0077_remove_usertestmodel_time_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestmodel',
            name='time_left',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
