# Generated by Django 3.2.4 on 2021-08-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0079_remove_usertestmodel_time_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestmodel',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
