# Generated by Django 3.2.4 on 2021-08-17 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0080_usertestmodel_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertestmodel',
            old_name='end_date',
            new_name='test_ending',
        ),
    ]
