# Generated by Django 3.2.4 on 2021-08-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0082_auto_20210818_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useransweredtheorylabmodel',
            name='points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
