# Generated by Django 3.2.4 on 2021-08-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0083_alter_useransweredtheorylabmodel_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='useransweredtestmodel',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useransweredtheorylabmodel',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
