# Generated by Django 3.2.4 on 2021-08-19 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0085_useransweredtestchaptermodel_answered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useransweredtestchaptermodel',
            name='user_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.usertestchaptermodel'),
        ),
    ]
