# Generated by Django 3.2.4 on 2021-08-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0086_alter_useransweredtestchaptermodel_user_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='useransweredtestchaptermodel',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
