# Generated by Django 3.2.4 on 2021-08-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0087_useransweredtestchaptermodel_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestmodel',
            name='trying',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
