# Generated by Django 3.2.6 on 2021-08-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0090_auto_20210826_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theorylabchaptermodel',
            old_name='telegram',
            new_name='trial',
        ),
        migrations.AddField(
            model_name='useransweredtheorylabmodel',
            name='github',
            field=models.TextField(blank=True, null=True),
        ),
    ]
