# Generated by Django 3.2.6 on 2021-08-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0091_auto_20210831_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='theorylabchaptermodel',
            name='type',
            field=models.IntegerField(choices=[(0, 'Replit'), (1, 'Github')], default=0),
            preserve_default=False,
        ),
    ]
