# Generated by Django 3.2.6 on 2021-08-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0092_theorylabchaptermodel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='theorylabchaptermodel',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
