# Generated by Django 3.2.6 on 2021-09-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0094_userboughtcoursemodel_trial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theorylabchaptermodel',
            name='text',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
