# Generated by Django 3.2.6 on 2021-09-16 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0096_auto_20210916_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodel',
            name='lesson',
        ),
        migrations.AddField(
            model_name='lessonmodel',
            name='recommend_end',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='courses.coursemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='preview',
            field=models.ImageField(default=None, upload_to='lesson/preview'),
            preserve_default=False,
        ),
    ]
