# Generated by Django 3.2.6 on 2021-09-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0097_auto_20210916_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlessonmodel',
            name='recommend_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
