# Generated by Django 3.2.6 on 2021-09-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0099_alter_projectmodel_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprojectmodel',
            name='project',
        ),
        migrations.RemoveField(
            model_name='userprojectmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='theorylabchaptermodel',
            name='project',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProjectModel',
        ),
        migrations.DeleteModel(
            name='UserProjectModel',
        ),
    ]
