# Generated by Django 3.2.6 on 2021-09-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0101_alter_userlessonoverallmodel_user_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergpahistory',
            name='gpa',
            field=models.FloatField(db_index=True),
        ),
    ]
