# Generated by Django 3.2.6 on 2021-09-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0102_alter_usergpahistory_gpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userboughtcoursemodel',
            name='gpa',
            field=models.FloatField(default=0),
        ),
    ]
