# Generated by Django 3.2.6 on 2021-09-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0103_alter_userboughtcoursemodel_gpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlessonmodel',
            name='gpa',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserGPAHistory',
        ),
    ]
