# Generated by Django 3.2.6 on 2021-09-20 09:13

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0104_auto_20210920_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGPAHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('gpa', models.FloatField(db_index=True)),
                ('user_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.userboughtcoursemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='usergpahistory',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at', 'updated_at'], name='courses_use_created_c654a1_brin'),
        ),
    ]
